### ISSUE TITLE
In some cases representation of bash scripts munged in report server output

### ISSUE THREAD

**Issue by dwcramer** [scalawag/jibe#17]
In the version of the script isPackageInstalled.sh (on the branch installAptPackage), the following line is truncated after `$pkg_name`:

```
CANDIDATE_PACKAGE_VERSION=$(apt-cache policy $pkg_name | grep Candidate | sed "s/  Candidate: //" )
```

See: https://www.dropbox.com/s/q32yz1et3xqk30t/Screenshot%202016-10-23%2000.14.43.png?dl=0

**Comment by justinp** [comment]
Is this just a UI problem or is it causing the script to fail?

**Comment by justinp** [comment]
Nevermind.  I figured it out.

**Comment by dwcramer** [comment]
Weird. I replied to the email and thought it was supposed to post to here.

**Comment by dwcramer** [comment]
UI only.
